### PR TITLE
App notification saver

### PR DESCRIPTION
**Pull request by 708yamaguchi**
I add `app_notification_saver` package, which saves notification json file according to service call.
For detail, please see https://github.com/708yamaguchi/app_manager_utils/blob/app-notification-saver/app_notification_saver/README.md

In addition, I use `app_notification_saver` in `mail_notifier_plugin`.
The sample output is like below:
```
Test app: 2021/07/28 (20:27:17)
===
Hi,
I succeeded in doing Test app.

Following object recognition is reported.
 - 2021-07-28T20:25:10 Dish is found
 - 2021-07-28T20:25:15 Dish is found
Following Navigation is reported.
 - 2021-07-28T20:25:20 Stucked in front of the chair
```

I will check this feature with go-to-kitchen demo tomorrow.

### CODE REVIEW

**Comment by knorth55** [comment]
cc. @mqcmd196

**Comment by mqcmd196** [comment]
+1

**Comment by 708yamaguchi** [comment]
I think `app_notification_server` works now.

Please see the email `Fetch kitchen patrol demo: 2021/07/29 (20:20:24)`
```
Hi,
I succeeded in doing Go to kitchen.
I succeeded to upload data.

URL: xxx

Following object recognition is reported.
 - 2021-07-29T20:18:45 (cup cup) is found.
```

@knorth55 
Could you review this PR?

**Comment by 708yamaguchi** [comment]
I add location information to the email like below:
```
Fetch kitchen patrol demo: 2021/07/29 (20:45:33)
===
Following object recognition is reported.
 - In kitchen at 2021-07-29T20:40:25, (kettle) is found.
```

**Review by knorth55 — APPROVED** [review]

**Pull request merged**
