### PR TITLE
Add smach notification

### PR DESCRIPTION
**Pull request by 708yamaguchi**
I add smach notification.

I will test this feature with go-to-kitchen demo tomorrow.

### CODE REVIEW

**Comment by knorth55** [comment]
can you split `launch` and `sample` for `rosbag` sample?

**Comment by 708yamaguchi** [comment]
OK, I split launch and sample.

**Review by knorth55 — APPROVED** [review]

**Comment by 708yamaguchi** [comment]
I tested smach notification again.
I checked that empty state is not reported.

```
Fetch kitchen patrol demo: 2021/07/30 (17:17:19)
===
Following smach is reported.
 - At 2021-07-30T17:12:14, Active states is REPORT-START-GO-TO-KITCHEN
 - At 2021-07-30T17:12:19, Active states is GET-LIGHT-ON
 - At 2021-07-30T17:12:19, Active states is REPORT-LIGHT-ON
 - At 2021-07-30T17:12:23, Active states is MOVE-TO-SINK-FRONT
 - At 2021-07-30T17:13:47, Active states is INSPECT-KITCHEN
 - At 2021-07-30T17:14:13, Active states is AUTO-DOCK
 - At 2021-07-30T17:15:42, Active states is ROOM-LIGHT-OFF
 - At 2021-07-30T17:15:43, Active states is FINISH

Following object recognition is reported.
 - In kitchen at 2021-07-30T17:13:51, (kettle cup dish) is found.
```

**Comment by 708yamaguchi** [comment]
I think this PR is OK to be merged.

I am very sorry for the additional commit after your review...

**Review by knorth55 — APPROVED** [review]

**Comment by knorth55** [comment]
Thanks, I merged this PR.

**Pull request merged**
